### ISSUE TITLE
Showing poll results to students

### ISSUE THREAD

**Issue by shubhbapna** [utmgdsc/PollVotingSystem#82]
**Is your feature request related to a problem? Please describe.**
Recently @embeddedt found out that we are sending the poll result message to students as well.
The product owner aka Prof Dan has decided to use these messages to display the vote results to students as well.
This feature request is to implement the same graph like vote results that profs see on the student side as well

**Describe the solution you'd like**
The students should only see the live vote results when the prof clicks a "show result" button.

- [ ] Add a new API that emits a message to student sockets that they can start showing the vote
- [ ] Add a button on the prof sides that calls the above API
- [ ] Display the graph of results once this new message is received. You can possibly refactor and use the same code that we use for prof's view to display the graph

**Additional context**
Lets discuss here and finalize the subtasks that need to be done and we will then assign the sub tasks.

**Deadline**
We need this to be done by end of December

**Comment by ggggg** [comment]
## Subtasks:

#### **Frontend:**

- [ ] Prof's view button to show results to students
- [ ] Students' view of the result (mostly done already, we can reuse the prof's view one as mentioned above)
- [ ] Students' way of showing/hiding results (for example, a button to show a pop-up like the prof's view, or we can come up with a new sidebar or something else)


#### **Backend:**

- [ ] Only send results to students once the prof presses the button (make sure it's not sent before the prof allows it to be sent)
- [ ] Handle prof's button input (the one to show results)


#### **To discuss:**

- [ ] Should instructors be allowed to show results to students while the poll is active, or only after the poll has ended?
- [ ] The design of the results panel (I would stick to the current design, but if you want a new design this is a good time to discuss it)

___

If possible, please assign me to some of these subtasks.

**Comment by huonggiangbui** [comment]
> ## Subtasks:
> #### **Frontend:**
> * [ ]  Prof's view button to show results to students
> * [ ]  Students' view of the result (mostly done already, we can reuse the prof's view one as mentioned above)
> * [ ]  Students' way of showing/hiding results (for example, a button to show a pop-up like the prof's view, or we can come up with a new sidebar or something else)
> 
> #### **Backend:**
> * [ ]  Only send results to students once the prof presses the button (make sure it's not sent before the prof allows it to be sent)
> * [ ]  Handle prof's button input (the one to show results)
> 
> #### **To discuss:**
> * [ ]  Should instructors be allowed to show results to students while the poll is active, or only after the poll has ended?
> * [ ]  The design of the results panel (I would stick to the current design, but if you want a new design this is a good time to discuss it)
> 
> If possible, please assign me to some of these subtasks.

You can hover to those subtasks - there should be "convert to issue" button on the right. Then you can comment on the new issues created from subtasks, and we can assign them to you!

**Comment by ggggg** [comment]
I would like to discuss the feature before we start working on it (see the to discuss) part.

**Comment by huonggiangbui** [comment]
> I would like to discuss the feature before we start working on it (see the to discuss) part.

Feel free to ping us on discord!

**Comment by shubhbapna** [comment]
@ggggg It doesn't matter if the poll has ended or not. The prof can choose to display the result by pressing the button at any point. Also I would like to stick with the current design of the results view
